/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PricesStruct = { yesPrice: BigNumberish; noPrice: BigNumberish };

export type PricesStructOutput = [yesPrice: bigint, noPrice: bigint] & {
  yesPrice: bigint;
  noPrice: bigint;
};

export interface PMAMMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "END_TIME"
      | "LIQUIDITY_FACTOR"
      | "MAX_PRICE"
      | "STARTING_PRICE"
      | "getEffectiveLiquidity"
      | "getPriceFromReserves"
      | "xReserve"
      | "yReserve"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "END_TIME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LIQUIDITY_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "STARTING_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFromReserves",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xReserve", values?: undefined): string;
  encodeFunctionData(functionFragment: "yReserve", values?: undefined): string;

  decodeFunctionResult(functionFragment: "END_TIME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDITY_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "STARTING_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFromReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yReserve", data: BytesLike): Result;
}

export interface PMAMM extends BaseContract {
  connect(runner?: ContractRunner | null): PMAMM;
  waitForDeployment(): Promise<this>;

  interface: PMAMMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  END_TIME: TypedContractMethod<[], [bigint], "view">;

  LIQUIDITY_FACTOR: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE: TypedContractMethod<[], [bigint], "view">;

  STARTING_PRICE: TypedContractMethod<[], [bigint], "view">;

  getEffectiveLiquidity: TypedContractMethod<[], [bigint], "view">;

  getPriceFromReserves: TypedContractMethod<[], [PricesStructOutput], "view">;

  xReserve: TypedContractMethod<[], [bigint], "view">;

  yReserve: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "END_TIME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDITY_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTING_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEffectiveLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceFromReserves"
  ): TypedContractMethod<[], [PricesStructOutput], "view">;
  getFunction(
    nameOrSignature: "xReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yReserve"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
