/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type MarketCreationDataStruct = {
  marketType: BigNumberish;
  creator: AddressLike;
  resolver: AddressLike;
  feeRecipient: AddressLike;
  platformFeeBps: BigNumberish;
  question: string;
  description: string;
  category: BigNumberish;
  subcategory: BigNumberish;
  endTime: BigNumberish;
};

export type MarketCreationDataStructOutput = [
  marketType: bigint,
  creator: string,
  resolver: string,
  feeRecipient: string,
  platformFeeBps: bigint,
  question: string,
  description: string,
  category: bigint,
  subcategory: bigint,
  endTime: bigint
] & {
  marketType: bigint;
  creator: string;
  resolver: string;
  feeRecipient: string;
  platformFeeBps: bigint;
  question: string;
  description: string;
  category: bigint;
  subcategory: bigint;
  endTime: bigint;
};

export type PricesStruct = { yesPrice: BigNumberish; noPrice: BigNumberish };

export type PricesStructOutput = [yesPrice: bigint, noPrice: bigint] & {
  yesPrice: bigint;
  noPrice: bigint;
};

export declare namespace IPredictionMarket {
  export type UserPositionStruct = {
    yesBalance: BigNumberish;
    noBalance: BigNumberish;
  };

  export type UserPositionStructOutput = [
    yesBalance: bigint,
    noBalance: bigint
  ] & { yesBalance: bigint; noBalance: bigint };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR"
      | "END_TIME"
      | "FEE_RECIPIENT"
      | "LIQUIDITY_FACTOR"
      | "MAX_PRICE"
      | "PLATFORM_FEE_BPS"
      | "PRESET_LIQUIDITY_FACTOR"
      | "RESOLVER"
      | "STARTING_PRICE"
      | "TOKEN"
      | "accumulatedFees"
      | "buy"
      | "claim"
      | "claimRefund"
      | "collateralPool"
      | "collectFees"
      | "description"
      | "forceClose"
      | "getBuyQuote"
      | "getEffectiveLiquidity"
      | "getMarketInfo"
      | "getPriceFromReserves"
      | "getSellQuote"
      | "getUserPosition"
      | "hasClaimed"
      | "invalidate"
      | "noShares"
      | "outcome"
      | "question"
      | "resolutionTime"
      | "resolve"
      | "sell"
      | "state"
      | "userPosition"
      | "xReserve"
      | "yReserve"
      | "yesShares"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Buy"
      | "FeesCollected"
      | "MarketInvalidated"
      | "MarketResolved"
      | "Sell"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "CREATOR", values?: undefined): string;
  encodeFunctionData(functionFragment: "END_TIME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FEE_RECIPIENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDITY_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRESET_LIQUIDITY_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RESOLVER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "STARTING_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TOKEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceClose",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyQuote",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFromReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "noShares", values?: undefined): string;
  encodeFunctionData(functionFragment: "outcome", values?: undefined): string;
  encodeFunctionData(functionFragment: "question", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolutionTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resolve", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "xReserve", values?: undefined): string;
  encodeFunctionData(functionFragment: "yReserve", values?: undefined): string;
  encodeFunctionData(functionFragment: "yesShares", values?: undefined): string;

  decodeFunctionResult(functionFragment: "CREATOR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "END_TIME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FEE_RECIPIENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDITY_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRESET_LIQUIDITY_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RESOLVER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "STARTING_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forceClose", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFromReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "invalidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "outcome", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "question", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolutionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yesShares", data: BytesLike): Result;
}

export namespace BuyEvent {
  export type InputTuple = [
    trader: AddressLike,
    isYes: boolean,
    shares: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    isYes: boolean,
    shares: bigint,
    cost: bigint
  ];
  export interface OutputObject {
    trader: string;
    isYes: boolean;
    shares: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketInvalidatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [outcome: boolean, timestamp: BigNumberish];
  export type OutputTuple = [outcome: boolean, timestamp: bigint];
  export interface OutputObject {
    outcome: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellEvent {
  export type InputTuple = [
    trader: AddressLike,
    isYes: boolean,
    shares: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    isYes: boolean,
    shares: bigint,
    cost: bigint
  ];
  export interface OutputObject {
    trader: string;
    isYes: boolean;
    shares: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR: TypedContractMethod<[], [string], "view">;

  END_TIME: TypedContractMethod<[], [bigint], "view">;

  FEE_RECIPIENT: TypedContractMethod<[], [string], "view">;

  LIQUIDITY_FACTOR: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PRESET_LIQUIDITY_FACTOR: TypedContractMethod<[], [bigint], "view">;

  RESOLVER: TypedContractMethod<[], [string], "view">;

  STARTING_PRICE: TypedContractMethod<[], [bigint], "view">;

  TOKEN: TypedContractMethod<[], [string], "view">;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [isYes: boolean, amount: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[], [bigint], "nonpayable">;

  claimRefund: TypedContractMethod<[], [bigint], "nonpayable">;

  collateralPool: TypedContractMethod<[], [bigint], "view">;

  collectFees: TypedContractMethod<[], [void], "nonpayable">;

  description: TypedContractMethod<[], [string], "view">;

  forceClose: TypedContractMethod<[], [void], "nonpayable">;

  getBuyQuote: TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        shares: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;

  getEffectiveLiquidity: TypedContractMethod<[], [bigint], "view">;

  getMarketInfo: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        PricesStructOutput,
        bigint,
        bigint,
        bigint
      ]
    ],
    "view"
  >;

  getPriceFromReserves: TypedContractMethod<[], [PricesStructOutput], "view">;

  getSellQuote: TypedContractMethod<
    [isYes: boolean, shares: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        cost: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [IPredictionMarket.UserPositionStructOutput],
    "view"
  >;

  hasClaimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  invalidate: TypedContractMethod<[], [void], "nonpayable">;

  noShares: TypedContractMethod<[], [bigint], "view">;

  outcome: TypedContractMethod<[], [boolean], "view">;

  question: TypedContractMethod<[], [string], "view">;

  resolutionTime: TypedContractMethod<[], [bigint], "view">;

  resolve: TypedContractMethod<[_outcome: boolean], [void], "nonpayable">;

  sell: TypedContractMethod<
    [isYes: boolean, shares: BigNumberish, minReturn: BigNumberish],
    [void],
    "nonpayable"
  >;

  state: TypedContractMethod<[], [bigint], "view">;

  userPosition: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { yesBalance: bigint; noBalance: bigint }],
    "view"
  >;

  xReserve: TypedContractMethod<[], [bigint], "view">;

  yReserve: TypedContractMethod<[], [bigint], "view">;

  yesShares: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "END_TIME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_RECIPIENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDITY_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRESET_LIQUIDITY_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLVER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STARTING_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [isYes: boolean, amount: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forceClose"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyQuote"
  ): TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        shares: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEffectiveLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        PricesStructOutput,
        bigint,
        bigint,
        bigint
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceFromReserves"
  ): TypedContractMethod<[], [PricesStructOutput], "view">;
  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<
    [isYes: boolean, shares: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        cost: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [IPredictionMarket.UserPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "invalidate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "noShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "outcome"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolutionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[_outcome: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [isYes: boolean, shares: BigNumberish, minReturn: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userPosition"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { yesBalance: bigint; noBalance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "xReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesShares"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Buy"
  ): TypedContractEvent<
    BuyEvent.InputTuple,
    BuyEvent.OutputTuple,
    BuyEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "MarketInvalidated"
  ): TypedContractEvent<
    MarketInvalidatedEvent.InputTuple,
    MarketInvalidatedEvent.OutputTuple,
    MarketInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Sell"
  ): TypedContractEvent<
    SellEvent.InputTuple,
    SellEvent.OutputTuple,
    SellEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "Buy(address,bool,uint256,uint256)": TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;
    Buy: TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;

    "FeesCollected(address,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "MarketInvalidated(uint256)": TypedContractEvent<
      MarketInvalidatedEvent.InputTuple,
      MarketInvalidatedEvent.OutputTuple,
      MarketInvalidatedEvent.OutputObject
    >;
    MarketInvalidated: TypedContractEvent<
      MarketInvalidatedEvent.InputTuple,
      MarketInvalidatedEvent.OutputTuple,
      MarketInvalidatedEvent.OutputObject
    >;

    "MarketResolved(bool,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "Sell(address,bool,uint256,uint256)": TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;
    Sell: TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;

    "WinningsClaimed(address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
