/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type MarketCreationDataStruct = {
  marketType: BigNumberish;
  creator: AddressLike;
  resolver: AddressLike;
  feeRecipient: AddressLike;
  platformFeeBps: BigNumberish;
  question: string;
  description: string;
  category: BigNumberish;
  subcategory: BigNumberish;
  endTime: BigNumberish;
};

export type MarketCreationDataStructOutput = [
  marketType: bigint,
  creator: string,
  resolver: string,
  feeRecipient: string,
  platformFeeBps: bigint,
  question: string,
  description: string,
  category: bigint,
  subcategory: bigint,
  endTime: bigint
] & {
  marketType: bigint;
  creator: string;
  resolver: string;
  feeRecipient: string;
  platformFeeBps: bigint;
  question: string;
  description: string;
  category: bigint;
  subcategory: bigint;
  endTime: bigint;
};

export interface PredictionMarketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TOKEN"
      | "allMarketsLength"
      | "approveResolver"
      | "approvedResolvers"
      | "createBinaryMarket"
      | "owner"
      | "revokeResolver"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "ResolverApproved"
      | "ResolverRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "TOKEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allMarketsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedResolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createBinaryMarket",
    values: [MarketCreationDataStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allMarketsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBinaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [marketAddress: AddressLike, creator: AddressLike];
  export type OutputTuple = [marketAddress: string, creator: string];
  export interface OutputObject {
    marketAddress: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverApprovedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverRevokedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketFactory;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TOKEN: TypedContractMethod<[], [string], "view">;

  allMarketsLength: TypedContractMethod<[], [bigint], "view">;

  approveResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  approvedResolvers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  createBinaryMarket: TypedContractMethod<
    [marketCreationData: MarketCreationDataStruct],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  revokeResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allMarketsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedResolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createBinaryMarket"
  ): TypedContractMethod<
    [marketCreationData: MarketCreationDataStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverApproved"
  ): TypedContractEvent<
    ResolverApprovedEvent.InputTuple,
    ResolverApprovedEvent.OutputTuple,
    ResolverApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverRevoked"
  ): TypedContractEvent<
    ResolverRevokedEvent.InputTuple,
    ResolverRevokedEvent.OutputTuple,
    ResolverRevokedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(address,address)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "ResolverApproved(address)": TypedContractEvent<
      ResolverApprovedEvent.InputTuple,
      ResolverApprovedEvent.OutputTuple,
      ResolverApprovedEvent.OutputObject
    >;
    ResolverApproved: TypedContractEvent<
      ResolverApprovedEvent.InputTuple,
      ResolverApprovedEvent.OutputTuple,
      ResolverApprovedEvent.OutputObject
    >;

    "ResolverRevoked(address)": TypedContractEvent<
      ResolverRevokedEvent.InputTuple,
      ResolverRevokedEvent.OutputTuple,
      ResolverRevokedEvent.OutputObject
    >;
    ResolverRevoked: TypedContractEvent<
      ResolverRevokedEvent.InputTuple,
      ResolverRevokedEvent.OutputTuple,
      ResolverRevokedEvent.OutputObject
    >;
  };
}
