/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type PricesStruct = { yesPrice: BigNumberish; noPrice: BigNumberish };

export type PricesStructOutput = [yesPrice: bigint, noPrice: bigint] & {
  yesPrice: bigint;
  noPrice: bigint;
};

export declare namespace IPredictionMarket {
  export type UserPositionStruct = {
    yesBalance: BigNumberish;
    noBalance: BigNumberish;
  };

  export type UserPositionStructOutput = [
    yesBalance: bigint,
    noBalance: bigint
  ] & { yesBalance: bigint; noBalance: bigint };
}

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "claim"
      | "claimRefund"
      | "getBuyQuote"
      | "getSellQuote"
      | "getUserPosition"
      | "invalidate"
      | "resolve"
      | "sell"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Buy"
      | "FeesCollected"
      | "MarketInvalidated"
      | "MarketResolved"
      | "Sell"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buy",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyQuote",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resolve", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invalidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
}

export namespace BuyEvent {
  export type InputTuple = [
    trader: AddressLike,
    isYes: boolean,
    shares: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    isYes: boolean,
    shares: bigint,
    cost: bigint
  ];
  export interface OutputObject {
    trader: string;
    isYes: boolean;
    shares: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketInvalidatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [outcome: boolean, timestamp: BigNumberish];
  export type OutputTuple = [outcome: boolean, timestamp: bigint];
  export interface OutputObject {
    outcome: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellEvent {
  export type InputTuple = [
    trader: AddressLike,
    isYes: boolean,
    shares: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    isYes: boolean,
    shares: bigint,
    cost: bigint
  ];
  export interface OutputObject {
    trader: string;
    isYes: boolean;
    shares: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<
    [isYes: boolean, amount: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[], [bigint], "nonpayable">;

  claimRefund: TypedContractMethod<[], [bigint], "nonpayable">;

  getBuyQuote: TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        shares: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;

  getSellQuote: TypedContractMethod<
    [isYes: boolean, shares: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        cost: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [IPredictionMarket.UserPositionStructOutput],
    "view"
  >;

  invalidate: TypedContractMethod<[], [void], "nonpayable">;

  resolve: TypedContractMethod<[outcome: boolean], [void], "nonpayable">;

  sell: TypedContractMethod<
    [isYes: boolean, shares: BigNumberish, minReturn: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [isYes: boolean, amount: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyQuote"
  ): TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        shares: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<
    [isYes: boolean, shares: BigNumberish],
    [
      [bigint, PricesStructOutput] & {
        cost: bigint;
        newPrices: PricesStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [IPredictionMarket.UserPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "invalidate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[outcome: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [isYes: boolean, shares: BigNumberish, minReturn: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Buy"
  ): TypedContractEvent<
    BuyEvent.InputTuple,
    BuyEvent.OutputTuple,
    BuyEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "MarketInvalidated"
  ): TypedContractEvent<
    MarketInvalidatedEvent.InputTuple,
    MarketInvalidatedEvent.OutputTuple,
    MarketInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Sell"
  ): TypedContractEvent<
    SellEvent.InputTuple,
    SellEvent.OutputTuple,
    SellEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "Buy(address,bool,uint256,uint256)": TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;
    Buy: TypedContractEvent<
      BuyEvent.InputTuple,
      BuyEvent.OutputTuple,
      BuyEvent.OutputObject
    >;

    "FeesCollected(address,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "MarketInvalidated(uint256)": TypedContractEvent<
      MarketInvalidatedEvent.InputTuple,
      MarketInvalidatedEvent.OutputTuple,
      MarketInvalidatedEvent.OutputObject
    >;
    MarketInvalidated: TypedContractEvent<
      MarketInvalidatedEvent.InputTuple,
      MarketInvalidatedEvent.OutputTuple,
      MarketInvalidatedEvent.OutputObject
    >;

    "MarketResolved(bool,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "Sell(address,bool,uint256,uint256)": TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;
    Sell: TypedContractEvent<
      SellEvent.InputTuple,
      SellEvent.OutputTuple,
      SellEvent.OutputObject
    >;

    "WinningsClaimed(address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
