/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarketFactory,
  IPredictionMarketFactoryInterface,
} from "../IPredictionMarketFactory";

const _abi = [
  {
    inputs: [],
    name: "BackdatedMarket",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDuration",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidEndTime",
    type: "error",
  },
  {
    inputs: [],
    name: "ResolverNotApproved",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "marketAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "resolver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "question",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "category",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "enum MarketType",
        name: "marketType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
    ],
    name: "MarketCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "resolver",
        type: "address",
      },
    ],
    name: "ResolverApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "resolver",
        type: "address",
      },
    ],
    name: "ResolverRevoked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "resolver",
        type: "address",
      },
    ],
    name: "approveResolver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum MarketType",
            name: "marketType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "address",
            name: "resolver",
            type: "address",
          },
          {
            internalType: "address",
            name: "feeRecipient",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "platformFeeBps",
            type: "uint16",
          },
          {
            internalType: "string",
            name: "question",
            type: "string",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "uint16",
            name: "category",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "subcategory",
            type: "uint16",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
        ],
        internalType: "struct MarketCreationData",
        name: "marketCreationData",
        type: "tuple",
      },
    ],
    name: "createBinaryMarket",
    outputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalMarketCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "resolver",
        type: "address",
      },
    ],
    name: "revokeResolver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint24",
        name: "duration",
        type: "uint24",
      },
    ],
    name: "setMaxMarketDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint24",
        name: "duration",
        type: "uint24",
      },
    ],
    name: "setMinMarketDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPredictionMarketFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketFactoryInterface {
    return new Interface(_abi) as IPredictionMarketFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarketFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPredictionMarketFactory;
  }
}
