/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarket,
  IPredictionMarketInterface,
} from "../IPredictionMarket";

const _abi = [
  {
    inputs: [],
    name: "Nimbus_AlreadyClaimed",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_InsufficientLiquidity",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_InvalidAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_MarketAlreadyResolved",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_MarketClosed",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_MarketNotClosed",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_MarketNotResolved",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_NoWinnings",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_SlippageExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_TooEarly",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_TransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "Nimbus_Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeesCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "MarketInvalidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bool",
        name: "outcome",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "MarketResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "trader",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bool",
        name: "isYes",
        type: "bool",
      },
      {
        indexed: true,
        internalType: "bool",
        name: "isBuy",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "cost",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "yesPrice",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "noPrice",
            type: "uint16",
          },
        ],
        indexed: false,
        internalType: "struct IPredictionMarket.Prices",
        name: "newPrices",
        type: "tuple",
      },
    ],
    name: "Trade",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WinningsClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isYes",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claim",
    outputs: [
      {
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimRefund",
    outputs: [
      {
        internalType: "uint256",
        name: "refund",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isYes",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "getBuyQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newPrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentPrices",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "yesPrice",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "noPrice",
            type: "uint16",
          },
        ],
        internalType: "struct IPredictionMarket.Prices",
        name: "prices",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isYes",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "getSellQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newPrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserPosition",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "yesBalance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "noBalance",
            type: "uint256",
          },
        ],
        internalType: "struct IPredictionMarket.UserPosition",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "invalidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "outcome",
        type: "bool",
      },
    ],
    name: "resolve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isYes",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minReturn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "sell",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPredictionMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketInterface {
    return new Interface(_abi) as IPredictionMarketInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarket {
    return new Contract(address, _abi, runner) as unknown as IPredictionMarket;
  }
}
