/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Gaussian,
  GaussianInterface,
} from "../../../@solstat/src/Gaussian";

const _abi = [
  {
    inputs: [],
    name: "Infinity",
    type: "error",
  },
  {
    inputs: [],
    name: "NegativeInfinity",
    type: "error",
  },
  {
    inputs: [],
    name: "OutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d165344cb267e5527f36c6f74221d92196d4d3331c8653db98fbd9d07ee67e3464736f6c634300081c0033";

type GaussianConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GaussianConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Gaussian__factory extends ContractFactory {
  constructor(...args: GaussianConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Gaussian & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Gaussian__factory {
    return super.connect(runner) as Gaussian__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GaussianInterface {
    return new Interface(_abi) as GaussianInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Gaussian {
    return new Contract(address, _abi, runner) as unknown as Gaussian;
  }
}
