/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type MarketCreationDataStruct = {
  marketType: BigNumberish;
  creator: AddressLike;
  resolver: AddressLike;
  feeRecipient: AddressLike;
  platformFeeBps: BigNumberish;
  question: string;
  description: string;
  category: BigNumberish;
  subcategory: BigNumberish;
  endTime: BigNumberish;
};

export type MarketCreationDataStructOutput = [
  marketType: bigint,
  creator: string,
  resolver: string,
  feeRecipient: string,
  platformFeeBps: bigint,
  question: string,
  description: string,
  category: bigint,
  subcategory: bigint,
  endTime: bigint
] & {
  marketType: bigint;
  creator: string;
  resolver: string;
  feeRecipient: string;
  platformFeeBps: bigint;
  question: string;
  description: string;
  category: bigint;
  subcategory: bigint;
  endTime: bigint;
};

export interface IPredictionMarketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveResolver"
      | "createBinaryMarket"
      | "getTotalMarketCount"
      | "revokeResolver"
      | "setMaxMarketDuration"
      | "setMinMarketDuration"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "ResolverApproved"
      | "ResolverRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createBinaryMarket",
    values: [MarketCreationDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMarketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxMarketDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinMarketDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBinaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMarketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxMarketDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinMarketDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketAddress: AddressLike,
    creator: AddressLike,
    resolver: AddressLike,
    question: string,
    category: BigNumberish,
    marketType: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    marketAddress: string,
    creator: string,
    resolver: string,
    question: string,
    category: bigint,
    marketType: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    marketAddress: string;
    creator: string;
    resolver: string;
    question: string;
    category: bigint;
    marketType: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverApprovedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverRevokedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPredictionMarketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarketFactory;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  createBinaryMarket: TypedContractMethod<
    [marketCreationData: MarketCreationDataStruct],
    [string],
    "nonpayable"
  >;

  getTotalMarketCount: TypedContractMethod<[], [bigint], "view">;

  revokeResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxMarketDuration: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinMarketDuration: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBinaryMarket"
  ): TypedContractMethod<
    [marketCreationData: MarketCreationDataStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTotalMarketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxMarketDuration"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinMarketDuration"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverApproved"
  ): TypedContractEvent<
    ResolverApprovedEvent.InputTuple,
    ResolverApprovedEvent.OutputTuple,
    ResolverApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverRevoked"
  ): TypedContractEvent<
    ResolverRevokedEvent.InputTuple,
    ResolverRevokedEvent.OutputTuple,
    ResolverRevokedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(address,address,address,string,uint16,uint8,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "ResolverApproved(address)": TypedContractEvent<
      ResolverApprovedEvent.InputTuple,
      ResolverApprovedEvent.OutputTuple,
      ResolverApprovedEvent.OutputObject
    >;
    ResolverApproved: TypedContractEvent<
      ResolverApprovedEvent.InputTuple,
      ResolverApprovedEvent.OutputTuple,
      ResolverApprovedEvent.OutputObject
    >;

    "ResolverRevoked(address)": TypedContractEvent<
      ResolverRevokedEvent.InputTuple,
      ResolverRevokedEvent.OutputTuple,
      ResolverRevokedEvent.OutputObject
    >;
    ResolverRevoked: TypedContractEvent<
      ResolverRevokedEvent.InputTuple,
      ResolverRevokedEvent.OutputTuple,
      ResolverRevokedEvent.OutputObject
    >;
  };
}
